name: admin
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase Plugins
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  webview_flutter_web: ^0.1.0+4
  webview_flutter: ^3.0.4
  dio: ^4.0.6
  bloc: ^7.2.1
  flutter_bloc: ^7.3.3
  logger: ^1.1.0
  flutter_dotenv: ^5.0.2
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/cover.png
