// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOVFYDqCdOqLMJd3B4lgrC0G46us4I8mQ',
    appId: '1:749634097629:web:58a1e10268fe838ae9e634',
    messagingSenderId: '749634097629',
    projectId: 'theiskaacom',
    authDomain: 'theiskaacom.firebaseapp.com',
    storageBucket: 'theiskaacom.appspot.com',
    measurementId: 'G-9HSB8BQK9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdttPxA8tcUBkslcqvzPMKSdMENLeVEDY',
    appId: '1:749634097629:android:b570a01c5374e8cce9e634',
    messagingSenderId: '749634097629',
    projectId: 'theiskaacom',
    storageBucket: 'theiskaacom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSMGKQiY4ou4iRsRK8YSYJ3j0iBl74Vpg',
    appId: '1:749634097629:ios:cae5c618660b9497e9e634',
    messagingSenderId: '749634097629',
    projectId: 'theiskaacom',
    storageBucket: 'theiskaacom.appspot.com',
    iosClientId: '749634097629-1deb0h8d784ev9up8lopeqadcind42lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSMGKQiY4ou4iRsRK8YSYJ3j0iBl74Vpg',
    appId: '1:749634097629:ios:cae5c618660b9497e9e634',
    messagingSenderId: '749634097629',
    projectId: 'theiskaacom',
    storageBucket: 'theiskaacom.appspot.com',
    iosClientId: '749634097629-1deb0h8d784ev9up8lopeqadcind42lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );
}
